const KEYWORD_COMPARISON = {
  // line 圖文資訊
  // 婚禮日期
  婚禮在什麼時候: "when",

  // 婚禮地點
  場地在哪裡: "where",

  // 婚禮座位
  婚禮當天我會坐哪裡: "seat",

  // 婚禮美照
  可以看一下婚紗照嗎: "pictures",

  // 出席問卷
  我可以去哪裡填問卷: "surveycake",

  // 祝福我們
  祝福我們: "blessing",

  // 自由發揮
  恭喜: "congregation",

  // 座位圖 start
  林泳秀: "14table",
  林柏甫: "14table",
  王婷譽: "14table",
  吳明純: "14table",
  林品綺: "14table",
  蔡侑辰: "14table",
  李書毅: "14table",
  李齊: "14table",
  林旻萱: "14table",
  沈陽傑: "14table",

  許維中: "15table",
  陳妤彤: "15table",
  任作哲: "15table",
  郭又禎: "15table",
  陳竑宇: "15table",
  張家齊: "15table",
  李振銘: "15table",
  邱如嫺: "15table",
  李蕙君: "15table",

  郭書榕: "16table",
  余承軒: "16table",
  劉品妤: "16table",
  戴佳儒: "16table",
  陳昕圓: "16table",
  林思妤: "16table",
  周子雅: "16table",
  羅勻廷: "16table",
  洪至韋: "16table",
  蔡名宣: "16table",

  林葳: "17table",
  柯昱任: "17table",
  洪敏豪: "17table",
  黃思齊: "17table",
  廖家緯: "17table",
  陳威志: "17table",
  練東霖: "17table",
  趙星豪: "17table",
  楊博喬: "17table",

  張楷侑: "34table",
  黃裕琇: "34table",
  傅家琳: "34table",
  蕭妤辰: "34table",
  陳宗佑: "34table",
  盧亦為: "34table",
  張伯宇: "34table",
  黃雋華: "34table",
  謝欣儒: "34table",

  劉宴汝: "36table",
  王晨蔚: "36table",
  黃順隆: "36table",
  周志康: "36table",
  郭維昌: "36table",
  許芊芊: "36table",
  王柏元: "36table",
  邱筱婷: "36table",
  江婉菱: "36table",
  陳珮珊: "36table",

  Vito: "37table",
  黃祥驊: "37table",
  Damien: "37table",
  盧禹丞: "37table",
  Peter: "37table",
  楊威澤: "37table",
  Jeff: "37table",
  小Jeff: "37table",
  趙知遠: "37table",
  Daniel: "37table",
  葉菘揚: "37table",
  Tony: "37table",
  徐磊: "37table",
  Molly: "37table",
  黃詩予: "37table",
  Jenny: "37table",
  陳俞臻: "37table",
  Brian: "37table",
  陳柏瑄: "37table",
  Bill: "37table",
  郭庭光: "37table",
  Herman: "37table",
  葉志健: "37table",

  Hank: "38table",
  林漢克: "38table",
  Wesley: "38table",
  吳慕云: "38table",
  Royal: "38table",
  陳柏融: "38table",
  Woody: "38table",
  張皓涵: "38table",
  Ding: "38table",
  陳財丁: "38table",
  Spencer: "38table",
  林宗翰: "38table",
  Samuel: "38table",
  莊盛州: "38table",
  Sam: "38table",
  楊俊生: "38table",
  Ben: "38table",
  郭俊毅: "38table",
  Zoey: "38table",
  沈曼鈞: "38table",

  馮儀芝: "21table",
  林書宜: "21table",
  莊雅雯: "21table",
  胡珊綺: "21table",
  鍾正剛: "21table",
  黃浩瑜: "21table",
  陳聖元: "21table",
  馮子薰: "21table",
  謝嘉允: "21table",
  莊旻錡: "21table",

  葉宇珊: "22table",
  邵薰誼: "22table",
  唐偉傑: "22table",
  吳聖輝: "22table",
  曾育萱: "22table",
  莊偉安: "22table",
  張雅琪: "22table",
  莊佳恩: "22table",
  高晨揚: "22table",

  陳誼珊: "23table",
  陳柏翔: "23table",
  林易萱: "23table",
  蔡秋圓: "23table",
  高宜鈴: "23table",
  林亦庭: "23table",
  賴怡婷: "23table",

  許雅雯: "24table",
  Blackrys: "24table",
  Beta: "24table",
  陳又寧: "24table",
  孫韻茹: "24table",
  Tasha: "24table",
  鄭守綱: "24table",
  Patrick: "24table",
  蔡旻憲: "24table",
  Kenny: "24table",

  陳俊宇: "28table",
  陳彥閔: "28table",
  陳宇倫: "28table",
  劉祐著: "28table",
  簡立昕: "28table",
  Shane: "28table",
  黃立軒: "28table",
  廖凰媛: "28table",
  何沂瑾: "28table",

  林致珈: "29table",
  周世軒: "29table",
  杜宥萱: "29table",
  張剛寧: "29table",
  王馨卉: "29table",
  王郁婷: "29table",
  陳玟臻: "29table",
  張心: "29table",
  黃耀立: "29table",

  羅珮綺: "30table",
  曾鈺涵: "30table",
  吳建錡: "30table",
  張驥宇: "30table",
  梅皓昀: "30table",
  吳佩汾: "30table",
  顏松柏: "30table",
  林昆佑: "30table",

  游靖宇: "31table",
  Yuly: "31table",
  王郁琪: "31table",
  Emily: "31table",
  林琬萍: "31table",
  皮皮: "31table",
  李明穎: "31table",
  李子: "31table",
  胡佳倩: "31table",
  佳佳: "31table",
  林孟如: "31table",
  小孟: "31table",
  // 座位圖 end

  笨蛋: "badWord",
  低能: "badWord",
  智障: "badWord",
  白痴: "badWord",
  醜: "badWord",

  阿珊好美: "bride",
  蓓珊好美: "bride",
  新娘好美: "bride",
  阿珊太美: "bride",
  蓓珊太美: "bride",
  新娘太美: "bride",
  阿珊超美: "bride",
  蓓珊超美: "bride",
  新娘超美: "bride",

  阿輝好帥: "bridegroom",
  輝輝好帥: "bridegroom",
  振輝好帥: "bridegroom",
  新郎好帥: "bridegroom",
  阿輝太帥: "bridegroom",
  輝輝太帥: "bridegroom",
  振輝太帥: "bridegroom",
  新郎太帥: "bridegroom",
  阿輝超帥: "bridegroom",
  輝輝超帥: "bridegroom",
  振輝超帥: "bridegroom",
  新郎超帥: "bridegroom",

  酒: "alcohol",

  感動: "touching",
  感人: "touching",

  王月: "moon",
  月亮: "moon",
};

const IGNORE_KEYWORD = [
  "when",
  "where",
  "seat",
  "pictures",
  "surveycake",
  "blessing",
  "14table",
  "15table",
  "16table",
  "17table",
  "21table",
  "22table",
  "23table",
  "24table",
  "28table",
  "29table",
  "30table",
  "31table",
  "34table",
  "36table",
  "37table",
  "38table",
];

module.exports = {
  KEYWORD_COMPARISON,
  IGNORE_KEYWORD,
};
